name = "Experimental Engineers Rebalanced & Fixed v2"
uid = "db1b5050-60c5-4c0c-8439-1427192b3b2h"
version = 1.2
copyright = "MXZ Mods 2009"
description = "Add Experimental Flying Engineers to all Factions. Reworked & Fixed by Mythixgirl - v1.2 fixed upload; delete previous version, credits to Mario P. and Chris S.."
author = "Mythixgirl"
icon = "/mods/ExpEngineers/modicon.png"
selectable = true
enabled = true
exclusive = false
ui_only = false
requires = {}
requiresNames = {}
conflicts = {}
before = {}
after = {}
